definitions:
  domain.PatchUserByMeRequest:
    properties:
      nickname:
        type: string
      resolution:
        type: string
    type: object
  domain.Provider:
    enum:
    - GOOGLE
    - APPLE
    - KAKAO
    type: string
    x-enum-varnames:
    - ProviderGoogle
    - ProviderApple
    - ProviderKakao
  presenter.FindUserByMeResponse:
    properties:
      id:
        type: integer
      nickname:
        type: string
      omitemtpy:
        type: string
      provider:
        $ref: '#/definitions/domain.Provider'
    type: object
info:
  contact: {}
paths:
  /users/me:
    get:
      consumes:
      - application/json
      description: Find user by me - ✅
      produces:
      - application/json
      responses:
        "200":
          description: 사용자 조회 성공
          schema:
            $ref: '#/definitions/presenter.FindUserByMeResponse'
      security:
      - BearerAuth: []
      summary: Find user by me
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Patch user by me - ✅
      parameters:
      - description: 사용자 수정 요청
        in: body
        name: PatchUserByMeRequest
        required: true
        schema:
          $ref: '#/definitions/domain.PatchUserByMeRequest'
      produces:
      - application/json
      responses:
        "204":
          description: 사용자 수정 성공
      security:
      - BearerAuth: []
      summary: Patch user by me
      tags:
      - User
swagger: "2.0"
